workflows - fail test

diff --git a/.github/workflows/build-matrix.yml b/.github/workflows/build-matrix.yml
--- a/.github/workflows/build-matrix.yml
+++ b/.github/workflows/build-matrix.yml
@@ -35,7 +35,12 @@ jobs:
           authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
 
       - name: Test
-        run: echo "Testing ${{ matrix.system }}"
+        run: |
+          echo "Testing ${{ matrix.system }}"
+          if [ "${{ matrix.system }}" = "aarch64-darwin" ]; then
+            echo "Failing on aarch64-darwin for testing"
+            exit 1
+          fi
 
       # - name: Build packages
       #   run: nix run nixpkgs#omnix -- ci run . --include-all-dependencies --systems ${{ matrix.system }}
